apps/user/urls.py
from django.urls import path
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.decorators import login_required
from apps.user.views import (register, index, Login, mythings, pendingth, madeth, save_thing,
    delete_thing, chang_stat, edit_thign, edit_th, view_th)

urlpatterns = [
	path('', index, name='index'),
    path('made/', madeth, name='madeth'),
    path('edit_th/', edit_th, name='edit_th'),
    path('view_th/', view_th, name='view_th'),
    path('register/', register, name='register'),
    path('mythings/', mythings, name='mythings'),
    path('pending/', pendingth, name='pendingth'),
    path('login/', Login.as_view(), name='login'),
    path('chang_stat/', chang_stat, name='chang_stat'),
    path('edit_thign/', edit_thign, name='edit_thign'),
    path('save_thing/', save_thing, name='save_thing'),
    path('delete_thing/', delete_thing, name='delete_thing'),
    path('logout/', login_required(logout_then_login), name='logout'),
    
]

todolist/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.user.urls', 'user'), namespace='user'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path(r'__debug__', include(debug_toolbar.urls)),
    ]

templates/main/main.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Todo List, organiza tus tareas pendientes">
    <meta name="author" content="OPTIC">
    <title>{% block title %} OPTIC - To Do List {% endblock %}</title>
    {% block metanet %} {% endblock %}
    {% block metafixed %} {% endblock %}
    {% block cssfixed %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}
    {% block cssunsettled %} {% endblock %}
    {% block metascriptfixed %}
        <script type="text/javascript" src="{% static 'js/all.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'public/js/things.js' %}"></script>
        <script type="text/javascript">
            {% if request.user.is_anonymous %}
                cache = sessionStorage;
                cache.clear();
            {% else %}
                cache = sessionStorage;
            {% endif %}
            function getChat(chat){
                return JSON.parse(cache.getItem(chat));
            }
            function setChat(chat, vl){
                cache.setItem(chat, JSON.stringify(vl));
            }
			$.ajaxSetup({ 
			    beforeSend: function(xhr, settings){
			        function getCookie(name){
			            var cookieValue = null;
			            if(document.cookie && document.cookie != ''){
			                var cookies = document.cookie.split(';');
			                for(var i = 0; i < cookies.length; i++){
			                     var cookie = jQuery.trim(cookies[i]);
			                     // Does this cookie string begin with the name we want?
			                     if (cookie.substring(0, name.length + 1) == (name + '=')){
			                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
			                         break;
			                     }
			                 }
			             }
			             return cookieValue;
			         }
			         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
			             // Only send the token to relative URLs i.e. locally.
			             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
			         }
			    } 
			});
			d2='{{ csrf_token }}';
        </script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	{% endblock %}
</head>

{% block bodybl %}
    <body>
{% endblock %}
    

    {% block scriptbase %}
    {% endblock  %}
    {% block startscript %}
    {% endblock  %}
    {% block header %}
    {% block menu %}
        <nav class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark">  
            <a class="navbar-brand" href="{% url 'user:index' %}" title="Inicio">OPTIC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item active">
                            <span class="nav-link">Bienvenido, {{ request.user.first_name }} {{ request.user.last_name }}</span>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Mis Tareas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'user:pendingth' %}">Pendientes</a>
                                <a class="dropdown-item" href="{% url 'user:madeth' %}">Realizadas</a>
                                <a class="dropdown-item" href="{% url 'user:mythings' %}">Todas</a>
                            </div>
                        </li>
                        
                        {% if request.user.is_superuser and request.user.is_staff %}
                            <li class="nav-item active">
                                <a target="_blank" class="nav-link" href="{% url 'admin:index' %}">Administrador</a>
                            </li>
                        {% endif %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:logout' %}">Cerrar Sesión</a>
                        </li>
                    {% else %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:login' %}">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:register' %}">Registrate</a>
                        </li>
                    {%endif%}
                </ul>
            </div>
        </nav>
    {% endblock %}
    
    {% endblock  %}
    {% block content %}
			
    {% endblock %}
    
    {% block modal %}
        
    {% endblock %}
    
    {% block modalfixed %}
        <div class="modal" id="view_thsp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="cond_th"><strong></strong></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="ststth"></div>
                    <div class="modal-body">
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="editthmo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-pk=''>
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="cond_th"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="ststth"></div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">To Do List:</label>
                                <textarea class="form-control" id="cont_th"></textarea>
                            </div>
                            <div class="form-check form-check-inline">
                                <input id="inp_edst" class="form-check-input" type="checkbox" id="inlineCheckbox1">
                                <label id="edit_status" class="form-check-label" for="inlineCheckbox1">Completa</label>
                            </div>
                            <div class="errorus text-center"></div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <div id="btn_edi_th" class="btn btn-primary edit_thi" data-typo="">Guardar</div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
        
</body>
</html>